name: Build and Release

on:
  push:
    branches:
      - 'releases/**'
    tags:
      - release-v*

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew shadowJar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
